const products = [
  {
    id: 1,
    name: "Eco-Friendly Stationery Set",
    description: "Complete stationery kit with recycled paper notebook and sustainable wooden pencils, perfect for eco-conscious students.",
    price: 89.99,
    originalPrice: 120.00,
    category: "Building Materials",
    image: `/Product/recycled-item1.jpg`,
    rating: 5,
    reviews: 127,
    isNew: true,
    discount: 25
  },
  {
    id: 2,
    name: "Recycled Glass Planter Vase",
    description: "Beautiful green glass vase perfect for small plants and herbs, crafted from 100% recycled glass materials.",
    price: 75.50,
    originalPrice: 95.00,
    category: "Building Materials",
    image: `/Product/recycled-item2.jpg`,
    rating: 4,
    reviews: 89,
    isNew: false,
    discount: 20
  },
  {
    id: 3,
    name: "Mandala Design Pen Holder",
    description: "Elegant wooden pen holder featuring intricate mandala pattern design, perfect for organizing desk accessories.",
    price: 34.99,
    originalPrice: 45.00,
    category: "Solar Products",
    image: `/Product/recycled-item3.jpg`,
    rating: 5,
    reviews: 203,
    isNew: false,
    discount: 22
  },
  {
    id: 4,
    name: "Recycled Material Storage Box",
    description: "Sturdy storage box made from recycled materials with vintage-style labeling, ideal for organizing documents and supplies.",
    price: 18.99,
    originalPrice: 25.00,
    category: "Eco Accessories",
    image: `/Product/recycled-item4.jpg`,
    rating: 4,
    reviews: 156,
    isNew: true,
    discount: 24
  },
  {
    id: 5,
    name: "Recycled Plastic Garden Bench",
    description: "Durable outdoor bench made from recycled plastic materials, weather-resistant and perfect for garden seating.",
    price: 12.75,
    originalPrice: 18.00,
    category: "Garden & Home",
    image: `/Product/recycled-item5.jpg`,
    rating: 5,
    reviews: 98,
    isNew: false,
    discount: 29
  },
  {
    id: 6,
    name: "Woven Natural Fiber Bowl",
    description: "Handcrafted bowl made from natural woven fibers, perfect for storing fruits or as decorative centerpiece.",
    price: 55.00,
    originalPrice: 70.00,
    category: "Building Materials",
    image: `/Product/recycled-item6.jpg`,
    rating: 4,
    reviews: 67,
    isNew: true,
    discount: 21
  },
  {
    id: 7,
    name: "Eco-Friendly Floor Mat",
    description: "Sustainable floor mat with geometric pattern, made from recycled materials and perfect for high-traffic areas.",
    price: 29.99,
    originalPrice: 40.00,
    category: "Packaging",
    image: `/Product/recycled-item7.jpg`,
    rating: 5,
    reviews: 134,
    isNew: false,
    discount: 25
  },
  {
    id: 8,
    name: "Reclaimed Wood Picture Frame",
    description: "Beautiful picture frame crafted from reclaimed wood with natural finish, perfect for displaying cherished memories.",
    price: 149.99,
    originalPrice: 200.00,
    category: "Building Materials",
    image: `/Product/recycled-item8.jpg`,
    rating: 5,
    reviews: 78,
    isNew: true,
    discount: 25
  },
  {
    id: 9,
    name: "Recycled Metal Sculpture Art",
    description: "Unique decorative metal sculpture crafted from recycled materials, perfect as a statement piece for modern interiors.",
    price: 24.99,
    originalPrice: 35.00,
    category: "Kitchen & Dining",
    image: `/Product/recycled-item9.jpg`,
    rating: 4,
    reviews: 92,
    isNew: true,
    discount: 29
  },
  {
    id: 10,
    name: "Upcycled Denim Wall Art",
    description: "Creative wall art piece made from upcycled denim materials, adding a unique textile element to any space.",
    price: 89.99,
    originalPrice: 120.00,
    category: "Home Decor",
    image: `/Product/recycled-item10.jpg`,
    rating: 5,
    reviews: 45,
    isNew: false,
    discount: 25
  },
  {
    id: 11,
    name: "Natural Cork Yoga Mat",
    description: "Premium eco-friendly yoga mat made from natural cork with excellent grip and cushioning for comfortable practice.",
    price: 65.99,
    originalPrice: 85.00,
    category: "Fitness & Wellness",
    image: `/Product/recycled-item11.jpg`,
    rating: 4,
    reviews: 156,
    isNew: true,
    discount: 22
  },
  {
    id: 12,
    name: "Sustainable Table Lamp",
    description: "Elegant table lamp with natural wood base and eco-friendly shade, providing warm ambient lighting for any room.",
    price: 299.99,
    originalPrice: 400.00,
    category: "Solar Products",
    image: `/Product/recycled-item12.jpg`,
    rating: 5,
    reviews: 67,
    isNew: true,
    discount: 25
  }
];

export default products;
